# Generated by Django 5.0.6 on 2024-07-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0003_product_minamount_product_amount_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Minamount',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
