# Generated by Django 5.0.6 on 2024-07-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0006_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
