# Generated by Django 5.1.2 on 2024-11-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0008_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
