# Generated by Django 5.1.2 on 2024-11-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0009_rename_crated_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='crated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='location',
        ),
    ]
